version: 2

defaults: &defaults
  working_directory: ~/project/vue
  docker:
    - image: vuejs/ci

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - v1-vue-{{ .Branch }}-
            - v1-vue-
      - run: yarn
      - save_cache:
          key: v1-vue-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
            - ~/.cache/yarn
            - ~/.cache/Cypress
      - persist_to_workspace:
          root: ~/project
          paths:
            - vue

  group-1:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test -p cli,cli-service,cli-shared-utils

  group-2:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test 'ts(?:\w(?!E2e))+\.spec\.js$'

  group-3:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn lint
      - run: yarn test -p cli-service-global,eslint,pwa,babel,babel-preset-app

  group-4:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: yarn test -p unit-mocha,unit-jest,e2e-nightwatch,e2e-cypress
      - run: yarn test tsPluginE2e

  cli-ui:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run: cd packages/@vue/cli-ui && yarn test
      - store_artifacts:
          path: packages/@vue/cli-ui/tests/e2e/videos
      - store_artifacts:
          path: packages/@vue/cli-ui/tests/e2e/screenshots

workflows:
  version: 2
  test:
    jobs:
      - install
      - group-1:
          requires:
            - install
      - group-2:
          requires:
            - install
      - group-3:
          requires:
            - install
      - group-4:
          requires:
            - install
      - cli-ui:
          requires:
            - install
